import type { PlayerManifest } from "./playerManifest.types";

export const sampleManifest: PlayerManifest = {
  episodeId: "sample-player",
  durationMs: 12800,
  tracks: [
    {
      id: "track-visual",
      name: "Visual",
      kind: "visual",
      layerId: 0,
      isMuted: false,
    },
    {
      id: "track-dialogue",
      name: "Dialogue",
      kind: "dialogue",
      layerId: 1,
      isMuted: false,
    },
    {
      id: "track-audio",
      name: "BGM",
      kind: "audio",
      layerId: 2,
      isMuted: false,
    },
    {
      id: "track-effect",
      name: "Effects",
      kind: "effect",
      layerId: 3,
      isMuted: false,
    },
  ],
  items: [
    {
      id: "visual-strip-1",
      trackId: "track-visual",
      kind: "visual",
      startTime: 0,
      endTime: 12000,
      mediaId: "media-strip-1",
      layerId: 0,
      volume: 1,
    },
    {
      id: "visual-cutaway-1",
      trackId: "track-visual",
      kind: "visual",
      startTime: 7800,
      endTime: 12800,
      mediaId: "media-cutaway-1",
      layerId: 1,
      volume: 1,
    },
    {
      id: "cue-item-5001",
      trackId: "track-dialogue",
      kind: "cue",
      startTime: 0,
      endTime: 2200,
      cueId: "cue-5001",
      layerId: 1,
      volume: 1,
    },
    {
      id: "cue-item-5002",
      trackId: "track-dialogue",
      kind: "cue",
      startTime: 2600,
      endTime: 6200,
      cueId: "cue-5002",
      layerId: 1,
      volume: 1,
    },
    {
      id: "cue-item-5003",
      trackId: "track-dialogue",
      kind: "cue",
      startTime: 7600,
      endTime: 10400,
      cueId: "cue-5003",
      layerId: 1,
      volume: 1,
    },
    {
      id: "effect-hit-1",
      trackId: "track-effect",
      kind: "effect",
      startTime: 7200,
      endTime: 7600,
      mediaId: "media-effect-1",
      layerId: 3,
      volume: 0.8,
    },
  ],
  cues: [
    {
      id: "cue-5001",
      scriptId: "script-5001",
      characterId: "character-hero",
      trackId: "track-dialogue",
      startTime: 0,
      endTime: 2200,
      approvedRecordUrl: "/audio/record-5001-approved.wav",
      ttsUrl: "/audio/tts-5001.wav",
      volume: 1,
    },
    {
      id: "cue-5002",
      scriptId: "script-5002",
      characterId: "character-guide",
      trackId: "track-dialogue",
      startTime: 2600,
      endTime: 6200,
      ttsUrl: "/audio/tts-5002.wav",
      volume: 0.92,
    },
    {
      id: "cue-5003",
      scriptId: "script-5003",
      characterId: "character-hero",
      trackId: "track-dialogue",
      startTime: 7600,
      endTime: 10400,
      approvedRecordUrl: "/audio/record-5003-approved.wav",
      ttsUrl: "/audio/tts-5003.wav",
      volume: 1,
    },
  ],
  media: [
    {
      id: "media-strip-1",
      kind: "image",
      url: "/media/strip-1.webp",
      naturalWidth: 690,
      naturalHeight: 4200,
    },
    {
      id: "media-cutaway-1",
      kind: "image",
      url: "/media/cutaway-1.webp",
      naturalWidth: 690,
      naturalHeight: 1380,
    },
    {
      id: "media-effect-1",
      kind: "effect",
      url: "/audio/effect-hit.wav",
      durationMs: 400,
    },
  ],
  records: [
    {
      id: "record-5001-approved",
      cueId: "cue-5001",
      artistId: "artist-1",
      status: "approved",
      audioUrl: "/audio/record-5001-approved.wav",
      durationMs: 2100,
      volume: 1,
    },
    {
      id: "record-5001-draft",
      cueId: "cue-5001",
      artistId: "artist-2",
      status: "draft",
      audioUrl: "/audio/record-5001-draft.wav",
      durationMs: 2300,
      volume: 0.9,
    },
    {
      id: "record-5003-approved",
      cueId: "cue-5003",
      artistId: "artist-1",
      status: "approved",
      audioUrl: "/audio/record-5003-approved.wav",
      durationMs: 2800,
      volume: 1,
    },
  ],
  tts: [
    {
      id: "tts-5001",
      cueId: "cue-5001",
      voiceId: "voice-hero",
      provider: "test-player",
      voiceName: "hero-ko",
      audioUrl: "/audio/tts-5001.wav",
    },
    {
      id: "tts-5002",
      cueId: "cue-5002",
      voiceId: "voice-guide",
      provider: "test-player",
      voiceName: "guide-ko",
      audioUrl: "/audio/tts-5002.wav",
    },
    {
      id: "tts-5003",
      cueId: "cue-5003",
      voiceId: "voice-hero",
      provider: "test-player",
      voiceName: "hero-ko",
      audioUrl: "/audio/tts-5003.wav",
    },
  ],
};
