import type { PlayerManifest } from './playerManifest.types';

export const sampleManifest: PlayerManifest = {
    episodeId: 1,
    durationMs: 12800,
    tracks: [
        {
            id: 1,
            name: 'Visual',
            kind: 'scroll',
            layerId: 0,
            isMuted: false,
        },
        {
            id: 2,
            name: 'Dialogue',
            kind: 'record',
            layerId: 1,
            isMuted: false,
        },
        {
            id: 3,
            name: 'BGM',
            kind: 'bgm',
            layerId: 2,
            isMuted: false,
        },
        {
            id: 4,
            name: 'Effects',
            kind: 'effect',
            layerId: 3,
            isMuted: false,
        },
    ],
    items: [
        {
            id: 101,
            trackId: 1,
            kind: 'visual',
            startTime: 0,
            endTime: 12000,
            mediaId: 201,
            layerId: 0,
            volume: 1,
        },
        {
            id: 102,
            trackId: 1,
            kind: 'visual',
            startTime: 7800,
            endTime: 12800,
            mediaId: 202,
            layerId: 1,
            volume: 1,
        },
        {
            id: 5001,
            trackId: 2,
            kind: 'cue',
            startTime: 0,
            endTime: 2200,
            cueId: 5001,
            layerId: 1,
            volume: 1,
        },
        {
            id: 5002,
            trackId: 2,
            kind: 'cue',
            startTime: 2600,
            endTime: 6200,
            cueId: 5002,
            layerId: 1,
            volume: 1,
        },
        {
            id: 5003,
            trackId: 2,
            kind: 'cue',
            startTime: 7600,
            endTime: 10400,
            cueId: 5003,
            layerId: 1,
            volume: 1,
        },
        {
            id: 9001,
            trackId: 4,
            kind: 'effect',
            startTime: 7200,
            endTime: 7600,
            mediaId: 301,
            layerId: 3,
            volume: 0.8,
        },
    ],
    cues: [
        {
            id: 5001,
            scriptId: 5001,
            characterId: 1,
            trackId: 2,
            startTime: 0,
            endTime: 2200,
            approvedRecordUrl: '/audio/record-5001.wav',
            ttsUrl: '/audio/tts-5001.wav',
            volume: 1,
        },
        {
            id: 5002,
            scriptId: 5002,
            characterId: 2,
            trackId: 2,
            startTime: 2600,
            endTime: 6200,
            ttsUrl: '/audio/tts-5002.wav',
            volume: 0.92,
        },
        {
            id: 5003,
            scriptId: 5003,
            characterId: 1,
            trackId: 2,
            startTime: 7600,
            endTime: 10400,
            approvedRecordUrl: '/audio/record-5003.wav',
            ttsUrl: '/audio/tts-5003.wav',
            volume: 1,
        },
    ],
    media: [
        {
            id: 201,
            kind: 'image',
            url: '/media/strip-1.webp',
            naturalWidth: 690,
            naturalHeight: 4200,
        },
        {
            id: 202,
            kind: 'image',
            url: '/media/cutaway-1.webp',
            naturalWidth: 690,
            naturalHeight: 1380,
        },
        {
            id: 301,
            kind: 'effect',
            url: '/audio/effect-hit.wav',
            durationMs: 400,
        },
    ],
    records: [
        {
            id: 6001,
            cueId: 5001,
            artistId: 1,
            recordUrl: '/audio/record-5001.wav',
            duration: 2100,
            volume: 1,
            isAccepted: true,
        },
        {
            id: 6003,
            cueId: 5003,
            artistId: 1,
            recordUrl: '/audio/record-5003.wav',
            duration: 2800,
            volume: 1,
            isAccepted: true,
        },
    ],
    tts: [
        {
            id: 7001,
            cueId: 5001,
            voiceId: 1,
            provider: 'test-player',
            voiceName: 'hero-ko',
            audioUrl: '/audio/tts-5001.wav',
        },
        {
            id: 7002,
            cueId: 5002,
            voiceId: 2,
            provider: 'test-player',
            voiceName: 'guide-ko',
            audioUrl: '/audio/tts-5002.wav',
        },
        {
            id: 7003,
            cueId: 5003,
            voiceId: 1,
            provider: 'test-player',
            voiceName: 'hero-ko',
            audioUrl: '/audio/tts-5003.wav',
        },
    ],
};
