import type { PlayerDraft } from "./player-draft.types";

export function createSamplePlayerDraft(): PlayerDraft {
  return {
    products: [
      {
        id: "product-100",
        title: "독립 테스트 작품",
        coverImageUrl: "/covers/sample-player.png",
      },
    ],
    episodes: [
      {
        id: "sample-player",
        productId: "product-100",
        episodeNumber: 1,
        title: "1화",
        subTitle: "timeline/cue manifest 검증",
      },
    ],
    characters: [
      {
        id: "character-hero",
        name: "주인공",
        color: "#2563eb",
        defaultTtsVoiceId: "voice-hero",
      },
      {
        id: "character-guide",
        name: "해설",
        color: "#16a34a",
        defaultTtsVoiceId: "voice-guide",
      },
    ],
    scripts: [
      {
        id: "script-5001",
        episodeId: "sample-player",
        characterId: "character-hero",
        text: "첫 번째 컷을 열어.",
        sortOrder: 1,
      },
      {
        id: "script-5002",
        episodeId: "sample-player",
        characterId: "character-guide",
        text: "이미지가 천천히 내려간다.",
        sortOrder: 2,
      },
      {
        id: "script-5003",
        episodeId: "sample-player",
        characterId: "character-hero",
        text: "효과음 뒤에 다음 장면으로.",
        sortOrder: 3,
      },
    ],
    tracks: [
      {
        id: "track-visual",
        episodeId: "sample-player",
        name: "Visual",
        kind: "visual",
        layerId: 0,
        isMuted: false,
      },
      {
        id: "track-dialogue",
        episodeId: "sample-player",
        name: "Dialogue",
        kind: "dialogue",
        layerId: 1,
        isMuted: false,
      },
      {
        id: "track-audio",
        episodeId: "sample-player",
        name: "BGM",
        kind: "audio",
        layerId: 2,
        isMuted: false,
      },
      {
        id: "track-effect",
        episodeId: "sample-player",
        name: "Effects",
        kind: "effect",
        layerId: 3,
        isMuted: false,
      },
    ],
    timelineItems: [
      {
        id: "visual-strip-1",
        trackId: "track-visual",
        kind: "visual",
        startTime: 0,
        endTime: 12000,
        mediaId: "media-strip-1",
        layerId: 0,
      },
      {
        id: "visual-cutaway-1",
        trackId: "track-visual",
        kind: "visual",
        startTime: 7800,
        endTime: 12800,
        mediaId: "media-cutaway-1",
        layerId: 1,
      },
      {
        id: "cue-item-5001",
        trackId: "track-dialogue",
        kind: "cue",
        startTime: 0,
        endTime: 2200,
        cueId: "cue-5001",
        layerId: 1,
      },
      {
        id: "cue-item-5002",
        trackId: "track-dialogue",
        kind: "cue",
        startTime: 2600,
        endTime: 6200,
        cueId: "cue-5002",
        layerId: 1,
      },
      {
        id: "cue-item-5003",
        trackId: "track-dialogue",
        kind: "cue",
        startTime: 7600,
        endTime: 10400,
        cueId: "cue-5003",
        layerId: 1,
      },
      {
        id: "effect-hit-1",
        trackId: "track-effect",
        kind: "effect",
        startTime: 7200,
        endTime: 7600,
        mediaId: "media-effect-1",
        layerId: 3,
        volume: 0.8,
      },
    ],
    media: [
      {
        id: "media-strip-1",
        episodeId: "sample-player",
        kind: "image",
        url: "/media/strip-1.webp",
        naturalWidth: 690,
        naturalHeight: 4200,
      },
      {
        id: "media-cutaway-1",
        episodeId: "sample-player",
        kind: "image",
        url: "/media/cutaway-1.webp",
        naturalWidth: 690,
        naturalHeight: 1380,
      },
      {
        id: "media-effect-1",
        episodeId: "sample-player",
        kind: "effect",
        url: "/audio/effect-hit.wav",
        durationMs: 400,
      },
    ],
    ttsVoices: [
      {
        id: "voice-hero",
        provider: "test-player",
        voiceName: "hero-ko",
        languageCode: "ko-KR",
      },
      {
        id: "voice-guide",
        provider: "test-player",
        voiceName: "guide-ko",
        languageCode: "ko-KR",
      },
    ],
    cues: [
      {
        id: "cue-5001",
        episodeId: "sample-player",
        scriptId: "script-5001",
        characterId: "character-hero",
        trackId: "track-dialogue",
        startTime: 0,
        endTime: 2200,
        ttsVoiceId: "voice-hero",
        ttsUrl: "/audio/tts-5001.wav",
        volume: 1,
      },
      {
        id: "cue-5002",
        episodeId: "sample-player",
        scriptId: "script-5002",
        characterId: "character-guide",
        trackId: "track-dialogue",
        startTime: 2600,
        endTime: 6200,
        ttsVoiceId: "voice-guide",
        ttsUrl: "/audio/tts-5002.wav",
        volume: 0.92,
      },
      {
        id: "cue-5003",
        episodeId: "sample-player",
        scriptId: "script-5003",
        characterId: "character-hero",
        trackId: "track-dialogue",
        startTime: 7600,
        endTime: 10400,
        ttsVoiceId: "voice-hero",
        ttsUrl: "/audio/tts-5003.wav",
        volume: 1,
      },
    ],
    records: [
      {
        id: "record-5001-approved",
        cueId: "cue-5001",
        artistId: "artist-1",
        status: "approved",
        audioUrl: "/audio/record-5001-approved.wav",
        durationMs: 2100,
        volume: 1,
      },
      {
        id: "record-5001-draft",
        cueId: "cue-5001",
        artistId: "artist-2",
        status: "draft",
        audioUrl: "/audio/record-5001-draft.wav",
        durationMs: 2300,
        volume: 0.9,
      },
      {
        id: "record-5003-approved",
        cueId: "cue-5003",
        artistId: "artist-1",
        status: "approved",
        audioUrl: "/audio/record-5003-approved.wav",
        durationMs: 2800,
        volume: 1,
      },
    ],
  };
}
